name: Build+Test & Documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Test
        uses: actions/checkout@v2
      - name: Build and Test
        uses: sersoft-gmbh/xcodebuild-action@v1.8.0
        with: 
          project: ReciPlease/ReciPlease.xcodeproj
          scheme: ReciPlease
          destination: platform=iOS Simulator
          enableCodeCoverage: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.2.1
  
  Documentaton:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Extract Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
           inputs: "ReciPlease/ReciPlease"
           module-name: MyLibrary
           output: "Documentation"
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
           path: "Documentation"
        env:
           GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
