name: Build+Test & Documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



jobs:

  iOS_15:
      name: Test iOS 15
      runs-on: macOS-latest
      strategy:
        matrix:
          destination: ["OS=15.0,name=iPhone 13 Pro"]
      steps:
        - uses: actions/checkout@v2
        - name: iOS - ${{ matrix.destination }}
          run: set -o pipefail && arch -arch arm64e env NSUnbufferedIO=YES xcodebuild -project "ReciPlease/ReciPlease.xcodeproj" -scheme "ReciPlease" -destination "${{ matrix.destination }}" 
               -enableCodeCoverage YES CODE_SIGNING_ALLOWED=NO clean build test | xcpretty
        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v1.2.1

  Documentaton:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate Documentation
      uses: SwiftDocOrg/swift-doc@master
      with:
         inputs: "ReciPlease/ReciPlease"
         module-name: MyLibrary
         output: "Documentation"
    - name: Upload Documentation to Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
         path: "Documentation"
      env:
         GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
         
         
