name: Codecov

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Test
        uses: actions/checkout@v1
      - name: Build and Test
        run:  xcodebuild test -project Reciplease-Beta/Reciplease-Beta.xcodeproj -scheme Reciplease-Beta -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.3' build test
