name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: Reciplease
          module-name: Reciplease
          format: html
          output: docs
      - name: Commit changes
        run: |
          git config --global user.email "documentation@githubaction.xyz"
          git config --global user.name "Documentation Action"
          git add -f docs
          git diff-index --quiet HEAD || git commit -m "auto update docs"
      - name: Push documentation
        run: git push -u origin main
