name: Build/Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: Reciplease.xcodeproj
        destination: "platform=iOS Simulator,name=iPhone 8"
        scheme: Reciplease
        action: build

  Documentaton:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract Documentation
      uses: SwiftDocOrg/swift-doc@master
      with:
         inputs: "Reciplease"
         module-name: MyLibrary
         output: "Documentation"
    - name: Upload Documentation to Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
         path: "Documentation"
      env:
         GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
